dist: xenial
language: node_js
node_js:
  - "10"
env:
    - NODE_ENV=test PORT=3001 JWT_SECRET_KEY=thisissecrtkey REDDIT_DB_CONNECTION="mysql://root@127.0.0.1/reddit"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS reddit;'
install:
  - npm install
script:
  - npm test