dist: xenial
sudo: true
language: node_js
node_js:
  - "10"
env:
    - NODE_ENV=test PORT=3001 JWT_SECRET_KEY=thisissecrtkey REDDIT_DB_CONNECTION="mysql://root@127.0.0.1/reddit" REDIS_HOST=localhost
REDIS_PORT=6379
services:
  - mysql
  - redis-server
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS reddit;'
install:
  - npm install
before_script:
  - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - sudo systemctl restart mysql
  - sudo mysql_upgrade
  - mysql --version  
script:
  - npm test